language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Sccripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-user-api ./udagram-user-api
  - docker tag udagram-user-api $DOCKER_USERNAME/udagram-user-api:latest
  - docker build -t udagram-feed-api ./udagram-feed-api
  - docker tag udagram-feed-api $DOCKER_USERNAME/udagram-feed-api:latest
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:latest
  - docker build -t udagram-reverse-proxy ./udagram-reverse-proxy
  - docker tag udagram-reverse-proxy $DOCKER_USERNAME/udagram-reverse-proxy:latest


# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/udagram-user-api
  - docker push $DOCKER_USERNAME/udagram-feed-api
  - docker push $DOCKER_USERNAME/udagram-frontend
  - docker push $DOCKER_USERNAME/udagram-reverse-proxy