apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-service
  labels:
    run: reverse-proxy-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    run: reverse-proxy-service