apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_USERNAME: 'david_legend'
  POSTGRES_PASSWORD: 'david_legend'
  POSTGRES_DB: 'postgres'
  POSTGRES_HOST: 'udagram-david-legend.cyqvcb5fkvjs.us-east-1.rds.amazonaws.com'
  PORT: '8082'
  AWS_REGION: 'us-east-1'
  AWS_PROFILE: 'default'
  AWS_BUCKET: 'udagram-david-legend'
  URL: ''
  JWT_SECRET: 'david_legend'





kubectl create secret generic backend-secret-vars --from-literal=POSTGRES_USERNAME=david_legend --from-literal=POSTGRES_PASSWORD=david_legend --from-literal=POSTGRES_HOST=udagram-david-legend.cyqvcb5fkvjs.us-east-1.rds.amazonaws.com --from-literal=AWS_REGION=us-east-1 --from-literal=AWS_PROFILE=default --from-literal=AWS_BUCKET=udagram-david-legend --from-literal=URL=url --from-literal=JWT_SECRET=david_legend --from-literal=PORT=8080